version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    groups:
      cargo:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/"
    groups:
      docker:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
