name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    uses: pkoenig10/workflows/.github/workflows/rust.yml@master

  docker:
    name: Docker
    uses: pkoenig10/workflows/.github/workflows/docker.yml@master
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
